# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b9aba20bf3816111978676851295acbdfe0f56ca12470a63770a348c9b493bad79174df3d655058ac354173513827c4459f0ab12cca9ef118f9adbff4f00e0d

test:
  secret_key_base: 59351c05bcf6e55cdaff0b379d5580ece1c9772ec732275018d95b6d7178cf85f8cc4559b7285de18dae71deea516dc258e51780975d88319708ab5186852b51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
